### ISSUE TITLE
Catch errors and create issues

### ISSUE THREAD

**Issue by wamesro** [Lakshan-Madushanka/Tracker#2]
It would be great if it catches errors and creates issues automatically such as Sentry or Laravel Telescope

**Comment by Lakshan-Madushanka** [comment]
@wamesro It wasn't part of the plan. This approach allows you can report errors/issues in a way that you understand, rather than solely relying on automated error reporting. However, automating this process would necessitate every site you build to use a plugin for connectivity and as you said there are tools out there for that. 

however that's not a bad idea, will consider it base on other reviews. Thanks for the idea
